
var eqwords = [
"Find Your Blindspots",
"Boost Your Productivity",
"Transform Your Career",
"Boost Your Productivity",
"Accelerate Your Growth",
"Transform Your Career",
"Achieve Your Goals",
"Transform Your Career",
"Find Your Blindspots",
"Accelerate Your Growth",
"Boost Your Productivity",
"Achieve Your Goals",
"Transform Your Career",
"Find Your Blindspots",
"Accelerate Your Growth",
"Boost Your Productivity",
"Transform Your Career",
"Find Your Blindspots",
"Boost Your Productivity",
"Transform Your Career",
"Boost Your Productivity",
"Accelerate Your Growth",
"Transform Your Career",
"Achieve Your Goals",
"Transform Your Career",
"Find Your Blindspots",
"Accelerate Your Growth",
"Boost Your Productivity",
"Achieve Your Goals",
"Transform Your Career",
"Find Your Blindspots",
"Accelerate Your Growth",
"Boost Your Productivity",
"Find Your Blindspots",
"Boost Your Productivity",
"Transform Your Career",
"Boost Your Productivity",
"Accelerate Your Growth",
"Transform Your Career",
"Achieve Your Goals",
"Transform Your Career",
"Find Your Blindspots",
"Accelerate Your Growth",
"Boost Your Productivity",
"Achieve Your Goals",
"Transform Your Career",
"Find Your Blindspots",
"Accelerate Your Growth",
"Boost Your Productivity",
"Find Your Blindspots",
"Boost Your Productivity",
"Transform Your Career",
"Boost Your Productivity",
"Accelerate Your Growth",
"Transform Your Career",
"Achieve Your Goals",
"Transform Your Career",
"Find Your Blindspots",
"Accelerate Your Growth",
"Boost Your Productivity",
"Achieve Your Goals",
"Transform Your Career",
"Find Your Blindspots",
"Accelerate Your Growth",
"Boost Your Productivity",
"Find Your Blindspots",
"Boost Your Productivity",
"Transform Your Career",
"Boost Your Productivity",
"Accelerate Your Growth",
"Transform Your Career",
"Achieve Your Goals",
"Transform Your Career",
"Find Your Blindspots",
"Accelerate Your Growth",
"Boost Your Productivity",
"Achieve Your Goals",
"Transform Your Career",
"Find Your Blindspots",
"Accelerate Your Growth",
"Boost Your Productivity",
"Find Your Blindspots",
"Boost Your Productivity",
"Transform Your Career",
"Boost Your Productivity",
"Accelerate Your Growth",
"Transform Your Career",
"Achieve Your Goals",
"Transform Your Career",
"Find Your Blindspots",
"Accelerate Your Growth",
"Boost Your Productivity",
"Achieve Your Goals",
"Transform Your Career",
"Find Your Blindspots",
"Accelerate Your Growth",
"Boost Your Productivity"
];

// get a random index, get the value from array and
// change the div content


     eqwords.forEach(function (entry) {
       $('#eqword').delay(1200).fadeToggle(400, function() {
           $(this).html(entry);
       });
     });
